service: tasks-api-serverless
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  stage: dev
  region: ap-south-1
  memorySize: 128
  logRetentionInDays: 1
  environment:
    TASKS_TABLE_NAME: !Ref TasksTable
    REGION: ${self:provider.region}
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

  httpApi:
    authorizers:
      tokenAuth:
        type: request
        identitySource:
          - $request.header.Authorization
        functionName: tokenAuthorizer

      jwtCognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        audience: ${self:custom.COGNITO_USER_POOL_CLIENT}
        issuerUrl:
          Fn::Join:
              - ""
              - - "https://cognito-idp."
                - "${opt:region, self:provider.region}"
                - ".amazonaws.com/"
                - ${self:custom.COGNITO_USER_POOL_ID}

functions:
  tokenAuthorizer:
    handler: src/authorizers/tokenAuthorizer.handler
  createNote:
    handler: src/handlers/createTask.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:PutItem
        Resource: !GetAtt TasksTable.Arn
    events:
      - httpApi:
          path: /tasks
          method: post
          authorizer: tokenAuth
  updateNote:
    handler: src/handlers/updateTask.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:UpdateItem
        Resource: !GetAtt TasksTable.Arn
    events:
      - httpApi:
          path: /tasks/{id}
          method: put
          authorizer: tokenAuth          
  getNotes:
    handler: src/handlers/getTasks.handler
    iamRoleStatementsInherit: true
    iamRoleStatements:
      - Effect: "Allow"
        Action:
          - dynamodb:Scan
        Resource: !GetAtt TasksTable.Arn
    events:
      - httpApi:
          path: /tasks
          method: get
          authorizer: jwtCognitoAuthorizer

plugins:
  - serverless-iam-roles-per-function

resources:
  Resources:
    TasksTable: ${file(resources/TaskTable.yml):TasksTable}
    CognitoUserPool: ${file(resources/Cognito.yml):CognitoUserPool}
    CognitoUserPoolClient: ${file(resources/Cognito.yml):CognitoUserPoolClient}
    CognitoUserPoolDomain: ${file(resources/Cognito.yml):CognitoUserPoolDomain}

custom:
  COGNITO_USER_POOL_ID: !Ref CognitoUserPool
  COGNITO_USER_POOL_CLIENT: !Ref CognitoUserPoolClient