# Cognito User Pool
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: TasksUserPool-${self:provider.stage}
    UsernameAttributes:
      - email

# Cognito User Pool Client
CognitoUserPoolClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref CognitoUserPool
    ClientName: WebClient-${self:provider.stage}
    AllowedOAuthFlowsUserPoolClient: true
    AllowedOAuthScopes:
      - email
      - profile
      - openid
    SupportedIdentityProviders:
      - COGNITO
    AllowedOAuthFlows:
      - implicit
    CallbackURLs:
      - http://localhost:3000
    DefaultRedirectURI: http://localhost:3000

# Cognito User Pool Domain
CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties: 
    Domain: tasksauthidp-${self:provider.stage}
    UserPoolId: !Ref CognitoUserPool
