# DynamoDB Tasks Table
TasksTable:
  Type: AWS::DynamoDB::Table
  Properties:
    AttributeDefinitions:
      - AttributeName: id
        AttributeType: N
    BillingMode: PAY_PER_REQUEST
    TableName: Tasks
    KeySchema:
      - AttributeName: id
        KeyType: HASH